### ISSUE TITLE
Index out of range error

### ISSUE THREAD

**Issue by zyfdegh** [liuxp0827/govpr#5]
I've replace wav files in `example/wav/train` with my own recordings and found an error when I rebuilt and run the example program.

```sh
./example
panic: runtime error: index out of range [62415] with length 62415

goroutine 1 [running]:
github.com/liuxp0827/govpr.(*VPREngine).AddTrainBuffer(0xc000098000, 0xc0000d402c, 0xf3cf, 0xf5cf, 0x0, 0x0)
	/Users/ferdi/GOPATH/src/github.com/liuxp0827/govpr/engine.go:163 +0x241
main.(*engine).TrainSpeech(0xc00000e038, 0xc000120000, 0x5, 0x8, 0x0, 0x0)
	/Users/ferdi/GOPATH/src/github.com/liuxp0827/govpr/example/main.go:31 +0x9d
main.main()
	/Users/ferdi/GOPATH/src/github.com/liuxp0827/govpr/example/main.go:95 +0x210
```

It's caused by the wrong range in a for loop, where `ii < length` should be `ii < length - 1` because it's used as `int16(buf[ii+1])` in the loop.
```sh
	for ii := 0; ii < length; ii += 2 {
		cBuff16 := int16(buf[ii])
		cBuff16 |= int16(buf[ii+1]) << 8
		sBuff = append(sBuff, cBuff16)
	}
```
Please have a look at the issue and I'm willing to send a PR.

**Comment by zyfdegh** [comment]
After I changed the code, and everything is OK. PR in #6
